---
- hosts: mininet
  serial: 1
  become: true
  become_user: root
  vars:
    GETH_BIN: "{{ GETH_BIN }}"

  tasks:
    - name: Run the Geth upgrade script on each server
      shell: ./upgrade_geth.sh {{ GETH_BIN }}
      args:
        chdir: /home/ec2-user
      register: result
      ignore_errors: yes
      async: 3600
      poll: 0

    - name: Wait for the upgrade to complete
      async_status:
        jid: "{{ result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 7

    - name: Collect output from each server
      set_fact:
        all_results: "{{ all_results | default([]) + [ { 'hostname': inventory_hostname, 'output': job_result.stdout } ] }}"

    - name: Print all results at the end
      debug:
        msg: |
          {% for result in all_results %}
          ====== {{ result.hostname }} ======
          {{ result.output }}
          {% endfor %}
      run_once: true