# This playbook is used to check the Geth version on all nodes
# It will run the 'geth version' command and display the output for each node.
# Usage: ansible-playbook geth_version_check.yml
---
- hosts: odyssey_velia
  become: false
  tasks:
    - name: Check if geth version
      command: geth version
      register: file_check_result
      ignore_errors: yes

    - name: Display result
      debug:
        var: file_check_result.stdout
