---
- name: Upgrade Cosmovisor Task
  hosts: all
  become: yes
  vars:
    user_home: "/home/ec2-user"
    version: ""
    bin_upgrade: ""
    upgrade_height: "" 
  
  
  tasks:
    - name: Ensure version to upgrade
      fail:
        msg: "Usage: Provide the version to run"
      when: version == ""

    - name: Ensure binary exists
      fail:
        msg: "Usage: Provide the binary name to run"
      when: bin_upgrade == ""

    - name: Ensure the specified upgrade block height
      fail:
        msg: "Usage: Provide the upgrade_height to run"
      when: upgrade_height == ""

    - name: Ensure binary has executable permissions
      file:
        path: "{{ user_home }}/{{ bin_upgrade }}"
        mode: '0755'
        state: file

    - name: Send the add upgrade plan
      command: cosmovisor add-upgrade {{ version }} {{ user_home }}/{{ bin_upgrade }} --force --upgrade-height {{ upgrade_height }}
      register: plan_result

    - name: Display the add upgrade result
      debug:
        var: plan_result.stdout

    - name: Check cosmovisor version after upgrade
      shell: |
        export DAEMON_NAME=story
        export DAEMON_HOME={{ user_home }}/story
        cosmovisor version
      register: cosmovisor_version


    - name: Display cosmovisor version after upgrade
      debug:
        var: cosmovisor_version.stdout